/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as BooksIdIndexRouteImport } from './routes/books/$id.index'
import { Route as BooksIdEditRouteImport } from './routes/books/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdIndexRoute = BooksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksIdRoute,
} as any)
const BooksIdEditRoute = BooksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$id': typeof BooksIdRouteWithChildren
  '/books': typeof BooksIndexRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/books/$id/': typeof BooksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksIndexRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/books/$id': typeof BooksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books/$id': typeof BooksIdRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/books/$id/': typeof BooksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$id' | '/books' | '/books/$id/edit' | '/books/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books' | '/books/$id/edit' | '/books/$id'
  id:
    | '__root__'
    | '/'
    | '/books/$id'
    | '/books/'
    | '/books/$id/edit'
    | '/books/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksIdRoute: typeof BooksIdRouteWithChildren
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id/': {
      id: '/books/$id/'
      path: '/'
      fullPath: '/books/$id/'
      preLoaderRoute: typeof BooksIdIndexRouteImport
      parentRoute: typeof BooksIdRoute
    }
    '/books/$id/edit': {
      id: '/books/$id/edit'
      path: '/edit'
      fullPath: '/books/$id/edit'
      preLoaderRoute: typeof BooksIdEditRouteImport
      parentRoute: typeof BooksIdRoute
    }
  }
}

interface BooksIdRouteChildren {
  BooksIdEditRoute: typeof BooksIdEditRoute
  BooksIdIndexRoute: typeof BooksIdIndexRoute
}

const BooksIdRouteChildren: BooksIdRouteChildren = {
  BooksIdEditRoute: BooksIdEditRoute,
  BooksIdIndexRoute: BooksIdIndexRoute,
}

const BooksIdRouteWithChildren =
  BooksIdRoute._addFileChildren(BooksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksIdRoute: BooksIdRouteWithChildren,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
